# Generated by Django 2.1.5 on 2019-02-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'Low priority'), ('reg', 'Regular'), ('sig', 'Significant'), ('urg', 'Urgent'), ('sev', 'Severe')], max_length=3)),
                ('employees', models.ManyToManyField(blank=True, related_name='scheduled_events', to='groups.EmployeeProfile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule_items', to='groups.EmployeeGroup')),
            ],
        ),
    ]
